# Generated by Django 4.2 on 2024-04-10 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="fiscal_year",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="webapp.fiscalyear",
            ),
            preserve_default=False,
        ),
    ]
