# Generated by Django 4.2 on 2024-03-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={'verbose_name': 'CustomerUser', 'verbose_name_plural': 'CustomerUsers'},
        ),
    ]
