# Generated by Django 4.2 on 2024-04-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_measure_fiscal_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='fiscal_year',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='fiscal_year',
        ),
    ]
