# Generated by Django 4.2 on 2024-03-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_customeruser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicinitiative',
            name='title',
            field=models.TextField(max_length=255),
        ),
    ]
