# Generated by Django 4.2 on 2024-04-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_mission_fiscal_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicinitiative',
            name='proposed_completion_date',
            field=models.DateField(),
        ),
    ]
