# Generated by Django 4.2 on 2024-04-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_focusarea_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusarea',
            name='create_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='focusarea',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='create_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='create_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quarterlyperformancedata',
            name='create_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quarterlyperformancedata',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='strategicinitiative',
            name='create_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='strategicinitiative',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='strategicinitiativedetail',
            name='create_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='strategicinitiativedetail',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
