# Generated by Django 4.2 on 2024-04-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_focusarea_create_by_focusarea_modified_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='focusarea',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='measure',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='objective',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='quarterlyperformancedata',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='strategicinitiative',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='strategicinitiativedetail',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
