# Generated by Django 4.2 on 2024-04-26 13:44

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_phone',
            field=webapp.validators.PhoneNumberField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='strategicinitiative',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
