# Generated by Django 4.2 on 2024-04-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_strategicinitiativedetail_expected_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='is_number',
            field=models.BooleanField(choices=[(True, 'Number'), (False, 'Rate')], default=False),
        ),
    ]
