# Generated by Django 4.2 on 2024-04-29 09:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_measure_is_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='target_rate',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
