# Generated by Django 4.2 on 2024-04-29 10:07

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_measure_target_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='target_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='target_rate',
            field=models.DecimalField(blank=True, decimal_places=0, default=Decimal('0'), max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
