# Generated by Django 4.2.11 on 2024-05-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_alter_profile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
