# Generated by Django 4.2.11 on 2024-05-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_customeruser_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='focusarea',
            field=models.ManyToManyField(default=1, null=True, related_name='objectives', to='webapp.focusarea'),
        ),
    ]
