# Generated by Django 4.2.11 on 2024-05-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_alter_objective_focusarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='focusarea',
            field=models.ManyToManyField(default=1, related_name='objectives', to='webapp.focusarea'),
        ),
    ]
