# Generated by Django 4.2.11 on 2024-05-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0026_remove_focusarea_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="focusarea",
            name="description",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
