# Generated by Django 4.2.11 on 2024-06-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0027_focusarea_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="grant_ext",
            field=models.BooleanField(default=False),
        ),
    ]
