# Generated by Django 4.2.11 on 2024-06-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0028_department_grant_ext"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="extension_granted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
