# Generated by Django 4.2.11 on 2024-07-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0030_remove_department_grant_ext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objective",
            name="name",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="strategicinitiative",
            name="title",
            field=models.TextField(max_length=500),
        ),
    ]
