# Generated by Django 4.2.11 on 2024-07-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0031_alter_objective_name_alter_strategicinitiative_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeruser",
            name="accessible_departments",
            field=models.ManyToManyField(
                blank=True, related_name="accessible_to_users", to="webapp.department"
            ),
        ),
        migrations.AddField(
            model_name="customeruser",
            name="is_global_performance_officer",
            field=models.BooleanField(default=False),
        ),
    ]
