# Generated by Django 4.2.11 on 2024-07-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0032_customeruser_accessible_departments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="is_number",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=False,
                verbose_name="Is this measure a number?",
            ),
        ),
    ]
