# Generated by Django 4.2.11 on 2024-07-26 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0035_alter_department_extension_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="extensionlog",
            name="requested_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="extensionlog",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logged_requested_extensions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="extensionlog",
            name="granted_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="extensionlog",
            name="granted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logged_granted_extensions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
