# Generated by Django 4.2.11 on 2024-07-30 10:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0036_extensionlog_requested_at_extensionlog_requested_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="current_year_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="target_number",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="target_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
