# Generated by Django 4.2.11 on 2024-07-30 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0037_alter_measure_current_year_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="target_number",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="target_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
