name: Sync main to deploy

on:
  push:
    branches:
      - main

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Sync main to deploy
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b deploy || git checkout deploy
          git reset --hard origin/main
          git push -f origin deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
