name: Sync main to deploy branch

on:
  push:
    branches:
      - main

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sync main to deploy branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout deploy
          git merge origin/main
          git push origin deploy
